name: "Compile"
description: "Executes a compilation."

inputs:
  path:
    required: true
    description: "Path to compile and test"
    default: src/
  build_path:
    required: true
    description: "Path to built files"

runs:
  steps:
    - name: "Test"
      run: echo "The input variable is: ${{ inputs.build_path }}"
    
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: ${{ inputs.build_path }}