name: "Compile"
description: "Executes a compilation."

inputs:
  path:
    required: true
    description: "Path to compile and test"
    default: src/
  build_path:
    required: true
    description: "Path to built files"

runs:
  using: "composite"
  steps:
    - name: "Test"
      run: |
        echo ${{ inputs.build_path }}
      shell: bash

    - name: Generate CMake project
      run: |
        SRC_FOLDER=$(pwd)/${{ inputs.path }}
        mkdir -p build-${{ inputs.build_path }} && cd build-${{ inputs.build_path }}
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          cmake ${SRC_FOLDER} -DBUILD_TESTS=1 -G "Visual Studio 17 2022" -A x64
        else
          cmake ${SRC_FOLDER} -DBUILD_TESTS=1 -G "Unix Makefiles"
        fi
        echo "CMake project generated in $(pwd)"
      shell: bash

    - name: Compile
      run: |
        cd build-${{ inputs.build_path }}
        if [ ! -f CMakeCache.txt ]; then
          echo "CMake cache not found in $(pwd). Aborting."
          exit 1
        fi
        cmake --build . --config RelWithDebInfo -j $(nproc)
      shell: bash

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: ${{ inputs.build_path }}