name: Compile

on:
    pull_request:
      types:
        - opened
        - synchronize
        - reopened

env:
  VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'

jobs:
  compile:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Run Compile Action
      uses: ./.github/actions/4_testintegration_compile
      with:
        path: src/
        build_path: build-${{ matrix.os }}/

#    - name: Run Tests
#      uses: ./.github/actions/4_testintegration_ctest
#      with:
#        path: build-${{ matrix.os }}/
