name: WorkflowC

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  await_workflow:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Dispatch an action and get the run ID
      uses: codex-/return-dispatch@v1
      id: return_dispatch
      with:
        token: ${{ github.token }}
        repo: wazuh-agent-test
        owner: xkazinx
        workflow: test_2.yml
    - name: Await Run ID ${{ steps.return_dispatch.outputs.run_id }}
      uses: Codex-/await-remote-run@v1.0.0
      with:
        token: ${{ github.token }}
        repo: wazuh-agent-test
        owner: xkazinx
        run_id: ${{ steps.return_dispatch.outputs.run_id }}
